### ISSUE TITLE
[ASK] MSI-GF63-9RCX i5 9300H type

### ISSUE THREAD

**Issue by aryayudha** [mledour/MSI-GF63-9RCX_OpenCore-Hackintosh#1]
Hi, can I use this for my i5 9300H with same model?

**Comment by mledour** [comment]
Hi, yes it should work

**Comment by radityabh** [comment]
@mledour with your efi i stuch in there, have solution? thanks
![IMG_20200808_171255](https://user-images.githubusercontent.com/15983827/89707690-c5815580-d99a-11ea-8b06-c02e3e17bdf8.jpg)

**Comment by mledour** [comment]
Have you ever make it working?
With mac os version are you usine?

**Comment by mledour** [comment]
And double check bios settings

**Comment by radityabh** [comment]
> Have you ever make it working?
> With mac os version are you usine?

yup, i use clover before. but laggy and hot.
Catalina 10.15.14

**Comment by mledour** [comment]
Try to enable `SetupVirtualMap` in config.plist

**Comment by radityabh** [comment]
> Have you turned off CFG Lock in bios?
> If not ty to enable `SetupVirtualMap` in config.plist

i don't find CFG Lock setting in my bios. 
i have try it, but its still same.

**Comment by radityabh** [comment]
Done, i setting AppleCpuPmCfgLock and AppleXcpmCfgLock to enable. Thanks you
