### ISSUE TITLE
[ASK] stuck on boot logo

### ISSUE THREAD

**Issue by darkbee101** [mledour/MSI-GF63-9RCX_OpenCore-Hackintosh#2]
Hey I just followed vanilla OC guide and added your EFI folder to the flash drive but i get stuck on apple logo
Any help?

**Comment by darkbee101** [comment]
Yes same laptop same specs.... i did chamge some stuff amd in config.plist and install macos fine but the weirdest issue is i cannot boot without usb even after copying the efi files

**Comment by mledour** [comment]
If you have the same laptop then keep config.plist untouched first to try to boot as it work fine for me.
Do you try to boot from the original laptop ssd?
Did you installed  macos 10.15.4?

**Comment by break98pl** [comment]
Hope update to MacOS 11 bigsur
