### ISSUE TITLE
[ASK] boot not detected on bios

### ISSUE THREAD

**Issue by aryayudha** [mledour/MSI-GF63-9RCX_OpenCore-Hackintosh#4]
Hi, thanks before for your great EFI. I followed your tutorial and have successfully installed mac os. But my mac is not detected in bios / boot order. I installed a mac with windows already installed on another hdd. please help

**Comment by mledour** [comment]
Hi,

Try to copy EFI/BOOT/BOOTx64.efi to EFI/Boot/Microsoft and rename it to bootmgfw.efi
It is a known bug of MSI bios to not discover BOOTx64.efi

**Comment by aryayudha** [comment]
Hi, thanks for your quick response. But this not solve my problem.

but finally I found a solution, by deleting the efi partition on the windows hdd.
